server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: modushield-demo-api

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
